# Generated by Django 5.2.17 on 2026-09-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="share_insights",
            field=models.BooleanField(default=False),
        ),
    ]
