# Generated by Django 5.2.17 on 2026-09-29 20:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("price_cents", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="BRL", max_length=3)),
                (
                    "interval",
                    models.CharField(
                        choices=[("month", "month"), ("year", "year")],
                        default="month",
                        max_length=8,
                    ),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                        ],
                        default="trialing",
                        max_length=12,
                    ),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(default="manual", max_length=20)),
                ("provider_ref", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="billing.plan",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="venues.venue",
                    ),
                ),
            ],
        ),
    ]
