// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    trips,
    weatherSnapshots,
    species,
    speciesNames,
    baits,
    gear,
    catches,
    catchPhotos,
    settings,
    jobs,
  ];
  late final Shape0 trips = Shape0(
    source: i0.VersionedTable(
      entityName: 'trips',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 weatherSnapshots = Shape1(
    source: i0.VersionedTable(
      entityName: 'weather_snapshots',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(trip_id)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_1,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 species = Shape2(
    source: i0.VersionedTable(
      entityName: 'species',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 speciesNames = Shape3(
    source: i0.VersionedTable(
      entityName: 'species_names',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 baits = Shape4(
    source: i0.VersionedTable(
      entityName: 'baits',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_37,
        _column_41,
        _column_16,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 gear = Shape4(
    source: i0.VersionedTable(
      entityName: 'gear',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_37,
        _column_41,
        _column_16,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 catches = Shape5(
    source: i0.VersionedTable(
      entityName: 'catches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_8,
        _column_9,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 catchPhotos = Shape6(
    source: i0.VersionedTable(
      entityName: 'catch_photos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 settings = Shape7(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_58, _column_59],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 jobs = Shape8(
    source: i0.VersionedTable(
      entityName: 'jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(kind, subject_id)'],
      columns: [
        _column_4,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_0,
        _column_1,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get syncStatus =>
      columnsByName['sync_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endedAt =>
      columnsByName['ended_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get timezone =>
      columnsByName['timezone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get latitude =>
      columnsByName['latitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get longitude =>
      columnsByName['longitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get locationAccuracyM =>
      columnsByName['location_accuracy_m']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get locationName =>
      columnsByName['location_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locationRegion =>
      columnsByName['location_region']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get privacyLevel =>
      columnsByName['privacy_level']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get moonPhase =>
      columnsByName['moon_phase']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get moonIllumination =>
      columnsByName['moon_illumination']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isRetroactive =>
      columnsByName['is_retroactive']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sync_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'pending\'',
      defaultValue: const i1.CustomExpression('\'pending\''),
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ended_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'timezone',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_8(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'latitude',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_9(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'longitude',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_10(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'location_accuracy_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'location_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'location_region',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'privacy_level',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'moon_phase',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_15(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'moon_illumination',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_retroactive',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_retroactive IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get tripId =>
      columnsByName['trip_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get temperatureC =>
      columnsByName['temperature_c']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get pressureHpa =>
      columnsByName['pressure_hpa']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get pressureTrend3hHpa =>
      columnsByName['pressure_trend3h_hpa']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get windSpeedKmh =>
      columnsByName['wind_speed_kmh']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get windDirectionDeg =>
      columnsByName['wind_direction_deg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get precipitationMm =>
      columnsByName['precipitation_mm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get humidityPct =>
      columnsByName['humidity_pct']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get hourlyJson =>
      columnsByName['hourly_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'trip_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES trips(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'fetched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_22(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'temperature_c',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_23(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'pressure_hpa',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_24(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'pressure_trend3h_hpa',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_25(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'wind_speed_kmh',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_26(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'wind_direction_deg',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_27(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'precipitation_mm',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_28(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'humidity_pct',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hourly_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get syncStatus =>
      columnsByName['sync_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scientificName =>
      columnsByName['scientific_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get habitats =>
      columnsByName['habitats']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get regionTags =>
      columnsByName['region_tags']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isCustom =>
      columnsByName['is_custom']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scientific_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'habitats',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'region_tags',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_custom',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_custom IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get speciesId =>
      columnsByName['species_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lang =>
      columnsByName['lang']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isPrimary =>
      columnsByName['is_primary']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get region =>
      columnsByName['region']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get needsReview =>
      columnsByName['needs_review']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'species_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES species(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'lang',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_primary',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_primary IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'region',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'needs_review',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (needs_review IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get syncStatus =>
      columnsByName['sync_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get archived =>
      columnsByName['archived']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'archived',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (archived IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get syncStatus =>
      columnsByName['sync_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tripId =>
      columnsByName['trip_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get speciesId =>
      columnsByName['species_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get caughtAt =>
      columnsByName['caught_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get weightG =>
      columnsByName['weight_g']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lengthMm =>
      columnsByName['length_mm']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get released =>
      columnsByName['released']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get baitId =>
      columnsByName['bait_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gearId =>
      columnsByName['gear_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get depthMm =>
      columnsByName['depth_mm']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get latitude =>
      columnsByName['latitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get longitude =>
      columnsByName['longitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'trip_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES trips(id)',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'species_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES species(id)',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'caught_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'weight_g',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'length_mm',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'released',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (released IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'bait_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES baits(id)',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'gear_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES gear(id)',
    );
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'depth_mm',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get syncStatus =>
      columnsByName['sync_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get catchId =>
      columnsByName['catch_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get relativePath =>
      columnsByName['relative_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get width =>
      columnsByName['width']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get height =>
      columnsByName['height']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get takenAt =>
      columnsByName['taken_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'catch_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES catches(id)',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'relative_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'width',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'height',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'taken_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subjectId =>
      columnsByName['subject_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get attempts =>
      columnsByName['attempts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nextAttemptAt =>
      columnsByName['next_attempt_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'subject_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_62(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attempts',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'next_attempt_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    trips,
    weatherSnapshots,
    species,
    speciesNames,
    baits,
    gear,
    catches,
    catchPhotos,
    settings,
    jobs,
    placeMaps,
  ];
  late final Shape0 trips = Shape0(
    source: i0.VersionedTable(
      entityName: 'trips',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 weatherSnapshots = Shape1(
    source: i0.VersionedTable(
      entityName: 'weather_snapshots',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(trip_id)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_1,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 species = Shape2(
    source: i0.VersionedTable(
      entityName: 'species',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 speciesNames = Shape3(
    source: i0.VersionedTable(
      entityName: 'species_names',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 baits = Shape4(
    source: i0.VersionedTable(
      entityName: 'baits',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_37,
        _column_41,
        _column_16,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 gear = Shape4(
    source: i0.VersionedTable(
      entityName: 'gear',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_37,
        _column_41,
        _column_16,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 catches = Shape5(
    source: i0.VersionedTable(
      entityName: 'catches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_8,
        _column_9,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 catchPhotos = Shape6(
    source: i0.VersionedTable(
      entityName: 'catch_photos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 settings = Shape7(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_58, _column_59],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 jobs = Shape8(
    source: i0.VersionedTable(
      entityName: 'jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(kind, subject_id)'],
      columns: [
        _column_4,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_0,
        _column_1,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 placeMaps = Shape9(
    source: i0.VersionedTable(
      entityName: 'place_maps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(area_key)'],
      columns: [
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_0,
        _column_1,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get areaKey =>
      columnsByName['area_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get centerLatitude =>
      columnsByName['center_latitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get centerLongitude =>
      columnsByName['center_longitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get halfSizeMeters =>
      columnsByName['half_size_meters']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get data =>
      columnsByName['data']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'area_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_66(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'center_latitude',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_67(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'center_longitude',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'half_size_meters',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'data',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    trips,
    weatherSnapshots,
    species,
    speciesNames,
    baits,
    gear,
    catches,
    catchPhotos,
    settings,
    jobs,
    placeMaps,
    venueCache,
  ];
  late final Shape10 trips = Shape10(
    source: i0.VersionedTable(
      entityName: 'trips',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_70,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 weatherSnapshots = Shape1(
    source: i0.VersionedTable(
      entityName: 'weather_snapshots',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(trip_id)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_1,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 species = Shape2(
    source: i0.VersionedTable(
      entityName: 'species',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 speciesNames = Shape3(
    source: i0.VersionedTable(
      entityName: 'species_names',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 baits = Shape4(
    source: i0.VersionedTable(
      entityName: 'baits',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_37,
        _column_41,
        _column_16,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 gear = Shape4(
    source: i0.VersionedTable(
      entityName: 'gear',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_37,
        _column_41,
        _column_16,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 catches = Shape5(
    source: i0.VersionedTable(
      entityName: 'catches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_8,
        _column_9,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 catchPhotos = Shape6(
    source: i0.VersionedTable(
      entityName: 'catch_photos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 settings = Shape7(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_58, _column_59],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 jobs = Shape8(
    source: i0.VersionedTable(
      entityName: 'jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(kind, subject_id)'],
      columns: [
        _column_4,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_0,
        _column_1,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 placeMaps = Shape9(
    source: i0.VersionedTable(
      entityName: 'place_maps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(area_key)'],
      columns: [
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_0,
        _column_1,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 venueCache = Shape11(
    source: i0.VersionedTable(
      entityName: 'venue_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_69, _column_71],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get syncStatus =>
      columnsByName['sync_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endedAt =>
      columnsByName['ended_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get timezone =>
      columnsByName['timezone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get latitude =>
      columnsByName['latitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get longitude =>
      columnsByName['longitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get locationAccuracyM =>
      columnsByName['location_accuracy_m']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get locationName =>
      columnsByName['location_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locationRegion =>
      columnsByName['location_region']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get privacyLevel =>
      columnsByName['privacy_level']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get moonPhase =>
      columnsByName['moon_phase']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get moonIllumination =>
      columnsByName['moon_illumination']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isRetroactive =>
      columnsByName['is_retroactive']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get venueId =>
      columnsByName['venue_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'venue_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get data =>
      columnsByName['data']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'fetched_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    trips,
    weatherSnapshots,
    species,
    speciesNames,
    baits,
    gear,
    catches,
    catchPhotos,
    settings,
    jobs,
    placeMaps,
    venueCache,
    outboxPosts,
  ];
  late final Shape10 trips = Shape10(
    source: i0.VersionedTable(
      entityName: 'trips',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_70,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 weatherSnapshots = Shape1(
    source: i0.VersionedTable(
      entityName: 'weather_snapshots',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(trip_id)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_1,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 species = Shape2(
    source: i0.VersionedTable(
      entityName: 'species',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 speciesNames = Shape3(
    source: i0.VersionedTable(
      entityName: 'species_names',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 baits = Shape4(
    source: i0.VersionedTable(
      entityName: 'baits',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_37,
        _column_41,
        _column_16,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 gear = Shape4(
    source: i0.VersionedTable(
      entityName: 'gear',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_37,
        _column_41,
        _column_16,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 catches = Shape5(
    source: i0.VersionedTable(
      entityName: 'catches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_8,
        _column_9,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 catchPhotos = Shape6(
    source: i0.VersionedTable(
      entityName: 'catch_photos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 settings = Shape7(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_58, _column_59],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 jobs = Shape8(
    source: i0.VersionedTable(
      entityName: 'jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(kind, subject_id)'],
      columns: [
        _column_4,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_0,
        _column_1,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 placeMaps = Shape9(
    source: i0.VersionedTable(
      entityName: 'place_maps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(area_key)'],
      columns: [
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_0,
        _column_1,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 venueCache = Shape11(
    source: i0.VersionedTable(
      entityName: 'venue_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_69, _column_71],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 outboxPosts = Shape12(
    source: i0.VersionedTable(
      entityName: 'outbox_posts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_60,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
        _column_70,
        _column_76,
        _column_77,
        _column_54,
        _column_55,
        _column_78,
        _column_0,
        _column_1,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get audience =>
      columnsByName['audience']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tripId =>
      columnsByName['trip_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get catchId =>
      columnsByName['catch_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get speciesId =>
      columnsByName['species_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get venueId =>
      columnsByName['venue_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get caption =>
      columnsByName['caption']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get imagePath =>
      columnsByName['image_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get width =>
      columnsByName['width']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get height =>
      columnsByName['height']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get error =>
      columnsByName['error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_72(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'audience',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'trip_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_74(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'catch_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_75(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'species_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_76(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'caption',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'image_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_78(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'error',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
  ),
);
