# Generated by Django 5.2.17 on 2026-09-29 09:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bait",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("server_seq", models.BigIntegerField(db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("type", models.CharField(max_length=24)),
                ("notes", models.TextField(blank=True, null=True)),
                ("archived", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Catch",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("server_seq", models.BigIntegerField(db_index=True)),
                ("species_id", models.CharField(blank=True, max_length=64, null=True)),
                ("caught_at", models.DateTimeField()),
                ("weight_g", models.IntegerField(blank=True, null=True)),
                ("length_mm", models.IntegerField(blank=True, null=True)),
                ("released", models.BooleanField(blank=True, null=True)),
                ("depth_mm", models.IntegerField(blank=True, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "bait",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logbook.bait",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CatchPhoto",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("server_seq", models.BigIntegerField(db_index=True)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("file_name", models.CharField(blank=True, max_length=200)),
                (
                    "catch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="logbook.catch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomSpecies",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("server_seq", models.BigIntegerField(db_index=True)),
                ("scientific_name", models.CharField(max_length=200)),
                ("habitats", models.CharField(blank=True, max_length=200)),
                ("region_tags", models.CharField(blank=True, max_length=200)),
                ("names", models.JSONField(default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Gear",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("server_seq", models.BigIntegerField(db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("type", models.CharField(max_length=24)),
                ("notes", models.TextField(blank=True, null=True)),
                ("archived", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="catch",
            name="gear",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logbook.gear",
            ),
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("server_seq", models.BigIntegerField(db_index=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(max_length=64)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("location_accuracy_m", models.FloatField(blank=True, null=True)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "location_region",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("privacy_level", models.CharField(max_length=16)),
                ("moon_phase", models.CharField(max_length=24)),
                ("moon_illumination", models.FloatField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_retroactive", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="catch",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catches",
                to="logbook.trip",
            ),
        ),
    ]
