# Generated by Django 5.2.17 on 2026-09-29 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logbook", "0002_sync_seq"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips",
                to="venues.venue",
            ),
        ),
    ]
