# Generated by Django 5.2.17 on 2026-09-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MapArea",
            fields=[
                (
                    "key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("body", models.BinaryField()),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
