targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          databases:
            app_database: lib/data/db/app_database.dart
          schema_dir: drift_schemas/
          test_dir: test/data/db/migrations/
      json_serializable:
        options:
          explicit_to_json: true
