# Generated by Django 5.2.17 on 2026-09-29 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=60, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("enabled", models.BooleanField(default=False)),
                ("rollout_percent", models.PositiveSmallIntegerField(default=100)),
                ("staff_only", models.BooleanField(default=False)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
